# The length of the trajectory in time domain, in seconds
trajectory_time_length: 6.0 # Trajectory length in seconds
curve_resample_step_size: 1.0 # Curve re-sampling step size in m
downsample_ratio: 12 # Amount to downsample input lanelet centerline data. Value corresponds to saving each nth point.
minimum_speed: 2.2352 # Minimum allowable speed in m/s
lookahead_count: 8 # Number of points to look ahead for speed reduction.
moving_average_window_size: 5 # Size of the window used in the moving average filter to smooth both the computed curvature and output speeds
curvature_calc_lookahead_count: 1 # Number of points to look ahead when calculating the curvature of the lanelet centerline
back_distance: 15.0 # Number of meters behind the first maneuver that need to be included in points for curvature calculation
max_accel_multiplier: 0.875 # TODO
lat_accel_multiplier: 0.05 # TODO