# Double: max cross track tolerance error
# Units: meter
max_crosstrack_error: 100000

# Double: downtrack_range
# Units: meter
destination_downtrack_range: -1000000

#for debug purposes
x: 318.0
y: -492.23