# Float: The minimum amount of time that an arbitrated plan must cover for the system to proceed with execution
# Unit: s
min_plan_duration: 6.0

# Float: The planning frequency for generation fo arbitrated plans
# Unit: Hz
planning_frequency: 1.0

# Integer: The width of the search beam to use for arbitrator planning, 1 = greedy search, as it approaches infinity
# the search approaches breadth-first search
# Unit: N/a
beam_width: 3

# Map: The priorities/costs associated with each plugin during the planning process
# Unit: N/a
plugin_priorities:
    autoware_plugin: 1.0
    glidepath_plugin: 5.0
